// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyUrl(arg1:string):Promise<void>;

export function ListFiles():Promise<Array<string>>;

export function NotifyUpdateImageList():Promise<void>;

export function SaveImage(arg1:string):Promise<void>;
