// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyAllUrls():Promise<void>;

export function CopyUrl(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetTargetDir():Promise<string>;

export function GetTemplate():Promise<string>;

export function ListFiles():Promise<Array<string>>;

export function NotifyUpdateImageList():Promise<void>;

export function SaveImage(arg1:string):Promise<void>;

export function SelectDir():Promise<string>;

export function SelectDirAndNotify():Promise<void>;

export function SetTargetDir(arg1:string):Promise<void>;

export function SetTemplate(arg1:string):Promise<void>;
