// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyUrl(arg1) {
  return window['go']['main']['App']['CopyUrl'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function NotifyUpdateImageList() {
  return window['go']['main']['App']['NotifyUpdateImageList']();
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function SelectDirAndNotify() {
  return window['go']['main']['App']['SelectDirAndNotify']();
}

export function SetTargetDir(arg1) {
  return window['go']['main']['App']['SetTargetDir'](arg1);
}

export function SetTemplate(arg1) {
  return window['go']['main']['App']['SetTemplate'](arg1);
}
